[package]
name = "sha256-rs"
version = "0.1.0"
edition = "2021"
description = "sha256 implementation in pure rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
